### ISSUE TITLE
Memory Display in Console

### ISSUE THREAD

**Issue by yogimathius** [yogimathius/core-war#18]
### Description

Implement a function to display a portion of the memory in the console, highlighting the current instruction pointer and executed instructions.

### Tasks

- [x] Write a function to display memory content.
- [x] Highlight the current instruction pointer.
- [x] Print executed instructions differently.
