### ISSUE TITLE
[EPIC] Execute Basic Instructions

### ISSUE THREAD

**Issue by yogimathius** [yogimathius/core-war#2]
### Description

Implement the execution logic for basic instructions like `live`, `ld`, `st`, etc.

### Completion Criteria

- [x] https://github.com/yogimathius/core-wars/issues/30
- [x] https://github.com/yogimathius/core-wars/issues/31
- [x] https://github.com/yogimathius/core-wars/issues/32
- [x] https://github.com/yogimathius/core-wars/issues/33
- [x] https://github.com/yogimathius/core-wars/issues/34
- [x] https://github.com/yogimathius/core-wars/issues/35
- [x] https://github.com/yogimathius/core-wars/issues/37
- [x] https://github.com/yogimathius/core-wars/issues/38
- [x] https://github.com/yogimathius/core-wars/issues/39
- [x] https://github.com/yogimathius/core-wars/issues/40
- [x] https://github.com/yogimathius/core-wars/issues/41
- [x] https://github.com/yogimathius/core-wars/issues/42
- [x] https://github.com/yogimathius/core-wars/issues/43
- [x] https://github.com/yogimathius/core-wars/issues/44
- [x] https://github.com/yogimathius/core-wars/issues/45
- [ ] https://github.com/yogimathius/core-wars/issues/36
