### ISSUE TITLE
Cycle Information Output

### ISSUE THREAD

**Issue by yogimathius** [yogimathius/core-war#20]
### Description

Implement a feature to output information about the current cycle, the number of cycles executed, and any changes in cycle-related parameters.

### Tasks

- [x] Print cycle information.
- [x] Display the number of cycles executed.
- [x] Output changes in cycle-related parameters.
