### ISSUE TITLE
[EPIC] Implement logic for operations

### ISSUE THREAD

**Issue by yogimathius** [yogimathius/core-war#46]
### Description

Implement the execution logic for basic instructions like `live`, `ld`, `st`, etc.

We can create a stub or placeholder for memory management to get started on these operations right away. This could be a basic data structure or array that simulates the memory space.

Using a TDD approach we can ensure each operation can be tested in isolation before full memory management is implemented.

### Completion Criteria

- [ ] https://github.com/yogimathius/core-wars/issues/30
- [x] https://github.com/yogimathius/core-wars/issues/31
- [x] https://github.com/yogimathius/core-wars/issues/32
- [x] https://github.com/yogimathius/core-wars/issues/33
- [x] https://github.com/yogimathius/core-wars/issues/34
- [x] https://github.com/yogimathius/core-wars/issues/35
- [x] https://github.com/yogimathius/core-wars/issues/37
- [x] https://github.com/yogimathius/core-wars/issues/38
- [x] https://github.com/yogimathius/core-wars/issues/39
- [x] https://github.com/yogimathius/core-wars/issues/40
- [x] https://github.com/yogimathius/core-wars/issues/41
- [ ] https://github.com/yogimathius/core-wars/issues/42
- [x] https://github.com/yogimathius/core-wars/issues/43
- [x] https://github.com/yogimathius/core-wars/issues/44
- [x] https://github.com/yogimathius/core-wars/issues/45
- [ ] https://github.com/yogimathius/core-wars/issues/36

**Comment by yogimathius** [comment]
Closing this as most are complete and the rest are being tracked in their own "Component" section
