### ISSUE TITLE
Handle add champion to VM

### ISSUE THREAD

**Issue by yogimathius** [yogimathius/core-war#56]
### Description

Using the [champion.c method add_champion](https://github.com/yogimathius/core-wars/blob/main/src/champion.c), complete a test in [champion_test.c](https://github.com/yogimathius/core-wars/blob/main/tests/champion_test.c#L8-L9) that asserts the virtualMachine.count == 1 and the champion is in the list of VM champions

### Tasks

- [x] Uncomment `add_champion` in champion.c to implement logic (don't forget to update unused to UNUSED)
- [x] add `test_add_champion` in `tests/champion_test.c` to implement test logic
- [x] initialize both VM and champion in test
- [x] call `add_champion` with vm and champ as args
- [x] assert vm.champion_count ==1 (will fail at first)
- [x] write logic in `add_champion` to increase count in vm
- [x] assert first champion in vm list of champions is just initialized champion (will fail at first)
- [x] write logic in `add_champion` to add champion to array of vm champions
