### ISSUE TITLE
[Refactor] - Write the header without any kinks

### ISSUE THREAD

**Issue by yogimathius** [yogimathius/core-war#79]
### Description

The header writing logic is a little hacky and could use some cleanup. Investigate how we can write it all to the cor file in one sweep, ideally as a struct (like in my_tar)

### Tasks

- [ ] `FileHeader` conformed to `header_t` struct in other `op.h`
- [ ] compiler logic cleaned up around parse_header function and other related header writing logic
- [ ] compiled cor file still accurately read in vm

**Comment by yogimathius** [comment]
de-prioritizing
